### ISSUE TITLE
Fix type error when navigating to user profiles

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#573]
```
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at U (/var/task/apps/site/.next/server/chunks/368.js:15:73154)
    at /var/task/apps/site/.next/server/chunks/368.js:15:70393
    at F (/var/task/apps/site/.next/server/chunks/368.js:15:72637)
    at B.request (/var/task/apps/site/.next/server/chunks/368.js:15:71481)
    at /var/task/apps/site/.next/server/chunks/228.js:312:607
    at w (/var/task/apps/site/.next/server/chunks/228.js:312:18)
    at Object.channelsItemsWithUser (/var/task/apps/site/.next/server/chunks/228.js:312:600)
    at /var/task/apps/site/.next/server/chunks/228.js:312:1897
    at AsyncLocalStorage.run (node:async_hooks:338:14)

**Comment by ioeylim** [comment]
Resolved with #580
